### ISSUE TITLE
Update to latest uaa version

### ISSUE THREAD

**Issue by thomasdarimont** [hortonworks/docker-cloudbreak-uaa#3]
The [cf-uaa](https://github.com/cloudfoundry/uaa) project has made some decent progress in the recent months - how about updating the Docker image definition?

**Comment by lalyos** [comment]
Sure, i will run some tests to check compatibility. 
@thomasdarimont do you think the db schema needs some migration?

**Comment by hannson** [comment]
Version 3.6.0 has serious security vulnerabilities.
